// this file is generated by generate.ps1
namespace Log73;
public static partial class Console {
public static void Info(object? value)
=> Logger.Info(value);
public static void Warn(object? value)
=> Logger.Warn(value);
public static void Error(object? value)
=> Logger.Error(value);
public static void Debug(object? value)
=> Logger.Debug(value);
public static void WriteLine(object? value)
=> Logger.WriteLine(value);
public static void Info(string? value)
=> Logger.Info(value);
public static void Warn(string? value)
=> Logger.Warn(value);
public static void Error(string? value)
=> Logger.Error(value);
public static void Debug(string? value)
=> Logger.Debug(value);
public static void WriteLine(string? value)
=> Logger.WriteLine(value);
public static void Info(ReadOnlySpan<char> value)
=> Logger.Info(value);
public static void Warn(ReadOnlySpan<char> value)
=> Logger.Warn(value);
public static void Error(ReadOnlySpan<char> value)
=> Logger.Error(value);
public static void Debug(ReadOnlySpan<char> value)
=> Logger.Debug(value);
public static void WriteLine(ReadOnlySpan<char> value)
=> Logger.WriteLine(value);
}

