// this file is generated by generate.ps1
namespace Log73;
public partial class Log73Logger {
public void Info(object? value)
=> PreWrite(value.ToString(), LogTypes.Info);
public void Warn(object? value)
=> PreWrite(value.ToString(), LogTypes.Warn);
public void Error(object? value)
=> PreWrite(value.ToString(), LogTypes.Error);
public void Debug(object? value)
=> PreWrite(value.ToString(), LogTypes.Debug);
public void WriteLine(object? value)
=> PreWrite(value.ToString(), LogTypes.WriteLine);
public void Info(string? value)
=> PreWrite(value, LogTypes.Info);
public void Warn(string? value)
=> PreWrite(value, LogTypes.Warn);
public void Error(string? value)
=> PreWrite(value, LogTypes.Error);
public void Debug(string? value)
=> PreWrite(value, LogTypes.Debug);
public void WriteLine(string? value)
=> PreWrite(value, LogTypes.WriteLine);
public void Info(ReadOnlySpan<char> value)
=> PreWrite(value, LogTypes.Info);
public void Warn(ReadOnlySpan<char> value)
=> PreWrite(value, LogTypes.Warn);
public void Error(ReadOnlySpan<char> value)
=> PreWrite(value, LogTypes.Error);
public void Debug(ReadOnlySpan<char> value)
=> PreWrite(value, LogTypes.Debug);
public void WriteLine(ReadOnlySpan<char> value)
=> PreWrite(value, LogTypes.WriteLine);
}

