name: Log73

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "6.0.x"
      - name: Build Log73
        run: dotnet build src/Log73 -c release
      - name: Build Log73.Markan
        run: dotnet build src/Log73.Markan -c release
      - name: Test Log73.Tests
        run: dotnet test src/Log73.Tests -c release